version: '3.8'

services:
  mysql:
    build: ./sql/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s && python3 ./crud.py"
    depends_on:
      - mysql
